### ISSUE TITLE
cannot setup galleon

### ISSUE THREAD

**Issue by sabr-p** [schahriar/Galleon#1]
just tried to install galleon, get a fatal error on the setup: 
TypeError: Cannot set property 'attachments' of undefined
    at PromptUI.completed (/usr/local/lib/node_modules/galleon/bin/tasks/setup.js:77:90)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/galleon/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at MergeObserver.onCompleted (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:3390:44)
    at MergeObserver.tryCatcher (/usr/local/lib/node_modules/galleon/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)

steps:
1 - sudo npm install -g galleon
2 - galleon setup
3 - enter some local domain name (local)
4 - leave both options (Save attachments, Store raw emails) selected
5 - error shows

versions: 
node v0.10.30
mongodb v3.0.4

if you need any other info, just ask   :)

**Comment by schahriar** [comment]
I've failed to reproduce the issue on v0.10.30 but the setup script is still very immature so I doubt there are any issues with your setup. I'll commit some improvements to prevent issues like this in the next few days but in the mean time you can check if you have the **.galleon** directory in your Home directory (cd ~/.galleon) with a **galleon.conf** file. If yes then delete the entire folder and try **galleon setup** again. The issue should not persist as the config variables only initially default to the existing config (if any) to prevent overrides every time _galleon setup_ is called. Let me know the result.

**Comment by sabr-p** [comment]
hey, thx for quick response  

so, did not have a galleon.conf file, but removed the dir anyway.
then, jumped to node 0.12.7, got a new error. 
then, unistalled, reinstalled with the 0.12.7, and it works. so, the build MUST be done with some minimum version. probably the one you have in your dev env  ;)

an update to the readme should save some pain to the slackers (like me) who update their VMs once in a century  :D

**Comment by schahriar** [comment]
Glad that it was fixed, let me know what environment/OS your are running. I have run tests on Ubuntu 12.04 and Ubuntu 14.04 with multiple versions of Node and yet I can't reproduce your initial issue.

**Comment by sabr-p** [comment]
the original environment was a 32bit, 3.18 kernel arch linux with 0.10.30 installed, this is where i got the error. then reinstalled/rebuilt on 0.12.7 and worked good.  

i  use the "n" package to test/jump node versions, and i'm not shy jumping from one to the other :)
also, it's a local testing VM, so i just hack it away without much care for stability. could have been some dependency that got updated too. so, don't loose any sleep over this one  :)

**Comment by Globik** [comment]
It would be nice to have a light version of galleon. Only for emails sending purposes.

**Comment by schahriar** [comment]
@Globik Galleon uses `smtp-connection` module for sending emails under the hood, I would definitely recommend taking a look at https://www.npmjs.com/package/nodemailer, Galleon serves the purpose of queuing and dispatching emails over a long period of time but I would love to revisit the API over the holidays if I can find the time.
